// Countries, regions of other countries and major world cities, written for this package from general knowledge.
// Enough to tell a foreign job from a US one and to name its country; @jobleft/static-data does the full gazetteer.

/** ISO 3166-1 alpha-2 -> names and common spellings (the first is the display name). */
export const COUNTRIES: Record<string, string[]> = {
  US: ['United States', 'United States of America', 'USA', 'U.S.A.', 'U.S.', 'US', 'America', 'Estados Unidos', 'EEUU', 'EE.UU.', 'Etats-Unis', 'États-Unis', 'Vereinigte Staaten'],
  CA: ['Canada', 'Kanada'],
  MX: ['Mexico', 'México', 'Mexique', 'Mexiko'],
  GB: ['United Kingdom', 'UK', 'U.K.', 'Great Britain', 'Britain', 'England', 'Scotland', 'Wales', 'Northern Ireland', 'Reino Unido', 'Royaume-Uni', 'Vereinigtes Königreich'],
  IE: ['Ireland', 'Republic of Ireland', 'Éire', 'Eire', 'Irlanda', 'Irlande'],
  DE: ['Germany', 'Deutschland', 'Alemania', 'Allemagne', 'Germania'],
  FR: ['France', 'Francia', 'Frankreich'],
  ES: ['Spain', 'España', 'Espana', 'Espagne', 'Spanien'],
  PT: ['Portugal'],
  IT: ['Italy', 'Italia', 'Italie', 'Italien'],
  NL: ['Netherlands', 'The Netherlands', 'Holland', 'Nederland', 'Países Bajos', 'Pays-Bas', 'Niederlande'],
  BE: ['Belgium', 'Belgique', 'België', 'Belgien', 'Bélgica'],
  LU: ['Luxembourg', 'Luxemburg'],
  CH: ['Switzerland', 'Schweiz', 'Suisse', 'Svizzera', 'Suiza'],
  AT: ['Austria', 'Österreich', 'Osterreich', 'Autriche'],
  DK: ['Denmark', 'Danmark', 'Dinamarca', 'Dänemark'],
  SE: ['Sweden', 'Sverige', 'Suecia', 'Suède', 'Schweden'],
  NO: ['Norway', 'Norge', 'Noruega', 'Norvège', 'Norwegen'],
  FI: ['Finland', 'Suomi', 'Finlandia', 'Finnland'],
  IS: ['Iceland', 'Ísland'],
  PL: ['Poland', 'Polska', 'Polonia', 'Pologne', 'Polen'],
  CZ: ['Czech Republic', 'Czechia', 'Česko', 'Česká republika', 'Tschechien'],
  SK: ['Slovakia', 'Slovensko'],
  HU: ['Hungary', 'Magyarország', 'Hungría', 'Ungarn'],
  RO: ['Romania', 'România', 'Rumania', 'Roumanie', 'Rumänien'],
  BG: ['Bulgaria', 'България'],
  GR: ['Greece', 'Hellas', 'Ελλάδα', 'Grecia', 'Grèce', 'Griechenland'],
  HR: ['Croatia', 'Hrvatska', 'Croacia'],
  SI: ['Slovenia', 'Slovenija'],
  RS: ['Serbia', 'Srbija', 'Србија'],
  BA: ['Bosnia and Herzegovina', 'Bosnia'],
  ME: ['Montenegro'],
  MK: ['North Macedonia', 'Macedonia'],
  AL: ['Albania', 'Shqipëria'],
  EE: ['Estonia', 'Eesti'],
  LV: ['Latvia', 'Latvija'],
  LT: ['Lithuania', 'Lietuva'],
  UA: ['Ukraine', 'Україна', 'Ucrania'],
  BY: ['Belarus'],
  MD: ['Moldova'],
  RU: ['Russia', 'Russian Federation', 'Россия', 'Rusia'],
  GE: ['Georgia (country)', 'Sakartvelo', 'საქართველო'],
  AM: ['Armenia'],
  AZ: ['Azerbaijan'],
  TR: ['Turkey', 'Türkiye', 'Turkiye', 'Turquía'],
  CY: ['Cyprus'],
  MT: ['Malta'],
  IL: ['Israel'],
  PS: ['Palestine'],
  LB: ['Lebanon', 'Liban'],
  JO: ['Jordan'],
  SA: ['Saudi Arabia', 'KSA', 'Kingdom of Saudi Arabia'],
  AE: ['United Arab Emirates', 'UAE', 'U.A.E.', 'Emirates'],
  QA: ['Qatar'],
  KW: ['Kuwait'],
  BH: ['Bahrain'],
  OM: ['Oman'],
  EG: ['Egypt', 'Egipto', 'Égypte'],
  MA: ['Morocco', 'Maroc', 'Marruecos'],
  TN: ['Tunisia', 'Tunisie'],
  DZ: ['Algeria', 'Algérie'],
  NG: ['Nigeria'],
  GH: ['Ghana'],
  KE: ['Kenya'],
  ET: ['Ethiopia'],
  UG: ['Uganda'],
  TZ: ['Tanzania'],
  RW: ['Rwanda'],
  ZA: ['South Africa', 'RSA'],
  SN: ['Senegal', 'Sénégal'],
  CI: ["Côte d'Ivoire", 'Ivory Coast'],
  CM: ['Cameroon'],
  IN: ['India', 'Bharat'],
  PK: ['Pakistan'],
  BD: ['Bangladesh'],
  LK: ['Sri Lanka'],
  NP: ['Nepal'],
  CN: ['China', "People's Republic of China", 'PRC', 'Mainland China', '中国'],
  HK: ['Hong Kong', 'Hong Kong SAR', 'HKSAR'],
  MO: ['Macau', 'Macao'],
  TW: ['Taiwan', '台灣', '台湾'],
  JP: ['Japan', '日本', 'Japón', 'Japon'],
  KR: ['South Korea', 'Korea', 'Republic of Korea', '대한민국', '한국', 'Corea del Sur'],
  SG: ['Singapore', 'Singapur'],
  MY: ['Malaysia'],
  ID: ['Indonesia'],
  TH: ['Thailand', 'ประเทศไทย'],
  VN: ['Vietnam', 'Viet Nam', 'Việt Nam'],
  PH: ['Philippines', 'Phlippines', 'Filipinas'],
  KH: ['Cambodia'],
  AU: ['Australia'],
  NZ: ['New Zealand', 'Aotearoa'],
  BR: ['Brazil', 'Brasil', 'Brésil', 'Brasilien'],
  AR: ['Argentina'],
  CL: ['Chile'],
  CO: ['Colombia', 'Kolumbien'],
  PE: ['Peru', 'Perú'],
  EC: ['Ecuador'],
  UY: ['Uruguay'],
  PY: ['Paraguay'],
  BO: ['Bolivia'],
  VE: ['Venezuela'],
  CR: ['Costa Rica'],
  PA: ['Panama', 'Panamá'],
  GT: ['Guatemala'],
  SV: ['El Salvador'],
  HN: ['Honduras'],
  NI: ['Nicaragua'],
  DO: ['Dominican Republic', 'República Dominicana'],
  JM: ['Jamaica'],
  TT: ['Trinidad and Tobago'],
  BS: ['Bahamas'],
  BB: ['Barbados'],
  KZ: ['Kazakhstan'],
  UZ: ['Uzbekistan'],
  MN: ['Mongolia'],
};

/** Macro regions a remote job may be limited to. */
export const MACRO_REGIONS: Record<string, string> = {
  'emea': 'EMEA', 'europe': 'EU', 'european union': 'EU', 'eu': 'EU', 'eea': 'EU', 'the eu': 'EU', 'europa': 'EU',
  'apac': 'APAC', 'asia pacific': 'APAC', 'asia-pacific': 'APAC', 'asia': 'APAC', 'latam': 'LATAM', 'latin america': 'LATAM',
  'south america': 'LATAM', 'central america': 'LATAM', 'americas': 'AMER', 'the americas': 'AMER', 'amer': 'AMER',
  'north america': 'NA', 'nam': 'NA', 'noram': 'NA', 'middle east': 'EMEA', 'mena': 'EMEA', 'africa': 'EMEA',
  'nordics': 'EU', 'dach': 'EU', 'benelux': 'EU', 'cee': 'EU', 'anz': 'APAC', 'oceania': 'APAC', 'uk and ireland': 'EU',
  'worldwide': 'WORLDWIDE', 'global': 'WORLDWIDE', 'anywhere': 'WORLDWIDE', 'anywhere in the world': 'WORLDWIDE',
  'international': 'WORLDWIDE', 'globally': 'WORLDWIDE',
};

/** Regions (states, provinces) of other countries: key -> [country, display name]. */
export const FOREIGN_REGIONS: Record<string, [string, string]> = {
  // Canada (codes are handled separately).
  'ontario': ['CA', 'Ontario'], 'quebec': ['CA', 'Quebec'], 'québec': ['CA', 'Quebec'], 'british columbia': ['CA', 'British Columbia'],
  'alberta': ['CA', 'Alberta'], 'manitoba': ['CA', 'Manitoba'], 'saskatchewan': ['CA', 'Saskatchewan'], 'nova scotia': ['CA', 'Nova Scotia'],
  'new brunswick': ['CA', 'New Brunswick'], 'newfoundland': ['CA', 'Newfoundland and Labrador'], 'newfoundland and labrador': ['CA', 'Newfoundland and Labrador'],
  'prince edward island': ['CA', 'Prince Edward Island'], 'yukon': ['CA', 'Yukon'], 'northwest territories': ['CA', 'Northwest Territories'], 'nunavut': ['CA', 'Nunavut'],
  // Australia.
  'new south wales': ['AU', 'New South Wales'], 'queensland': ['AU', 'Queensland'], 'western australia': ['AU', 'Western Australia'],
  'south australia': ['AU', 'South Australia'], 'tasmania': ['AU', 'Tasmania'], 'australian capital territory': ['AU', 'Australian Capital Territory'],
  'northern territory': ['AU', 'Northern Territory'], 'nsw': ['AU', 'NSW'], 'qld': ['AU', 'QLD'], 'vic': ['AU', 'VIC'], 'tas': ['AU', 'TAS'], 'act': ['AU', 'ACT'],
  // UK nations and English regions.
  'england': ['GB', 'England'], 'scotland': ['GB', 'Scotland'], 'wales': ['GB', 'Wales'], 'northern ireland': ['GB', 'Northern Ireland'],
  'greater london': ['GB', 'Greater London'], 'west midlands': ['GB', 'West Midlands'], 'east midlands': ['GB', 'East Midlands'],
  'greater manchester': ['GB', 'Greater Manchester'], 'west yorkshire': ['GB', 'West Yorkshire'], 'south yorkshire': ['GB', 'South Yorkshire'],
  'merseyside': ['GB', 'Merseyside'], 'tyne and wear': ['GB', 'Tyne and Wear'], 'hertfordshire': ['GB', 'Hertfordshire'],
  'buckinghamshire': ['GB', 'Buckinghamshire'], 'berkshire': ['GB', 'Berkshire'], 'oxfordshire': ['GB', 'Oxfordshire'],
  'cambridgeshire': ['GB', 'Cambridgeshire'], 'surrey': ['GB', 'Surrey'], 'kent': ['GB', 'Kent'], 'essex': ['GB', 'Essex'],
  'sussex': ['GB', 'Sussex'], 'hampshire': ['GB', 'Hampshire'], 'lancashire': ['GB', 'Lancashire'], 'yorkshire': ['GB', 'Yorkshire'],
  // India.
  'karnataka': ['IN', 'Karnataka'], 'maharashtra': ['IN', 'Maharashtra'], 'telangana': ['IN', 'Telangana'], 'tamil nadu': ['IN', 'Tamil Nadu'],
  'haryana': ['IN', 'Haryana'], 'uttar pradesh': ['IN', 'Uttar Pradesh'], 'gujarat': ['IN', 'Gujarat'], 'kerala': ['IN', 'Kerala'],
  'west bengal': ['IN', 'West Bengal'], 'rajasthan': ['IN', 'Rajasthan'], 'punjab': ['IN', 'Punjab'], 'andhra pradesh': ['IN', 'Andhra Pradesh'],
  'madhya pradesh': ['IN', 'Madhya Pradesh'], 'odisha': ['IN', 'Odisha'], 'delhi ncr': ['IN', 'Delhi NCR'], 'ncr': ['IN', 'NCR'],
  'national capital region': ['IN', 'NCR'], 'goa': ['IN', 'Goa'],
  // Mexico.
  'jalisco': ['MX', 'Jalisco'], 'nuevo leon': ['MX', 'Nuevo León'], 'nuevo león': ['MX', 'Nuevo León'], 'cdmx': ['MX', 'CDMX'],
  'estado de mexico': ['MX', 'Estado de México'], 'estado de méxico': ['MX', 'Estado de México'], 'queretaro': ['MX', 'Querétaro'],
  'querétaro': ['MX', 'Querétaro'], 'quintana roo': ['MX', 'Quintana Roo'], 'baja california': ['MX', 'Baja California'],
  'yucatan': ['MX', 'Yucatán'], 'yucatán': ['MX', 'Yucatán'], 'puebla': ['MX', 'Puebla'], 'guanajuato': ['MX', 'Guanajuato'],
  'chihuahua': ['MX', 'Chihuahua'], 'sonora': ['MX', 'Sonora'], 'coahuila': ['MX', 'Coahuila'], 'jal': ['MX', 'Jalisco'],
  // Brazil.
  'sao paulo state': ['BR', 'São Paulo'], 'rio de janeiro state': ['BR', 'Rio de Janeiro'], 'minas gerais': ['BR', 'Minas Gerais'],
  'parana': ['BR', 'Paraná'], 'paraná': ['BR', 'Paraná'], 'santa catarina': ['BR', 'Santa Catarina'], 'rio grande do sul': ['BR', 'Rio Grande do Sul'],
  'bahia': ['BR', 'Bahia'], 'pernambuco': ['BR', 'Pernambuco'], 'ceara': ['BR', 'Ceará'], 'ceará': ['BR', 'Ceará'], 'goias': ['BR', 'Goiás'],
  'goiás': ['BR', 'Goiás'], 'espirito santo': ['BR', 'Espírito Santo'], 'espírito santo': ['BR', 'Espírito Santo'], 'maranhao': ['BR', 'Maranhão'],
  'maranhão': ['BR', 'Maranhão'], 'para': ['BR', 'Pará'], 'amazonas': ['BR', 'Amazonas'], 'distrito federal': ['BR', 'Distrito Federal'],
  'federal district': ['BR', 'Distrito Federal'],
  // Germany.
  'bavaria': ['DE', 'Bavaria'], 'bayern': ['DE', 'Bayern'], 'berlin state': ['DE', 'Berlin'], 'hesse': ['DE', 'Hesse'], 'hessen': ['DE', 'Hessen'],
  'north rhine-westphalia': ['DE', 'North Rhine-Westphalia'], 'north rhine westphalia': ['DE', 'North Rhine-Westphalia'],
  'nordrhein-westfalen': ['DE', 'Nordrhein-Westfalen'], 'nordrhein westfalen': ['DE', 'Nordrhein-Westfalen'], 'baden-württemberg': ['DE', 'Baden-Württemberg'],
  'baden wurttemberg': ['DE', 'Baden-Württemberg'], 'baden württemberg': ['DE', 'Baden-Württemberg'], 'lower saxony': ['DE', 'Lower Saxony'],
  'niedersachsen': ['DE', 'Niedersachsen'], 'saxony': ['DE', 'Saxony'], 'sachsen': ['DE', 'Sachsen'], 'brandenburg': ['DE', 'Brandenburg'],
  'hamburg state': ['DE', 'Hamburg'], 'schleswig-holstein': ['DE', 'Schleswig-Holstein'], 'rhineland-palatinate': ['DE', 'Rhineland-Palatinate'],
  'thuringia': ['DE', 'Thuringia'],
  // Others commonly written in job boards.
  'ile-de-france': ['FR', 'Île-de-France'], 'île-de-france': ['FR', 'Île-de-France'], 'ile de france': ['FR', 'Île-de-France'],
  'auvergne-rhone-alpes': ['FR', 'Auvergne-Rhône-Alpes'], 'provence-alpes-cote d\'azur': ['FR', "Provence-Alpes-Côte d'Azur"],
  'catalonia': ['ES', 'Catalonia'], 'cataluña': ['ES', 'Cataluña'], 'catalunya': ['ES', 'Catalunya'], 'community of madrid': ['ES', 'Community of Madrid'],
  'comunidad de madrid': ['ES', 'Comunidad de Madrid'], 'andalusia': ['ES', 'Andalusia'], 'valencian community': ['ES', 'Valencian Community'],
  'basque country': ['ES', 'Basque Country'], 'lombardy': ['IT', 'Lombardy'], 'lombardia': ['IT', 'Lombardia'], 'lazio': ['IT', 'Lazio'],
  'tuscany': ['IT', 'Tuscany'], 'toscana': ['IT', 'Toscana'], 'piedmont': ['IT', 'Piedmont'], 'emilia-romagna': ['IT', 'Emilia-Romagna'],
  'veneto': ['IT', 'Veneto'], 'north holland': ['NL', 'North Holland'], 'noord-holland': ['NL', 'Noord-Holland'], 'south holland': ['NL', 'South Holland'],
  'zuid-holland': ['NL', 'Zuid-Holland'], 'utrecht province': ['NL', 'Utrecht'], 'masovian voivodeship': ['PL', 'Masovian Voivodeship'],
  'mazowieckie': ['PL', 'Mazowieckie'], 'lesser poland': ['PL', 'Lesser Poland'], 'małopolskie': ['PL', 'Małopolskie'],
  'guangdong': ['CN', 'Guangdong'], 'guangdong province': ['CN', 'Guangdong'], 'zhejiang': ['CN', 'Zhejiang'], 'jiangsu': ['CN', 'Jiangsu'],
  'sichuan': ['CN', 'Sichuan'], 'metro manila': ['PH', 'Metro Manila'], 'national capital region philippines': ['PH', 'NCR'],
  'tel aviv district': ['IL', 'Tel Aviv District'], 'central district': ['IL', 'Central District'], 'haifa district': ['IL', 'Haifa District'],
  'jerusalem district': ['IL', 'Jerusalem District'], 'brussels-capital': ['BE', 'Brussels-Capital'], 'brussels capital region': ['BE', 'Brussels-Capital'],
  'flanders': ['BE', 'Flanders'], 'wallonia': ['BE', 'Wallonia'], 'zurich canton': ['CH', 'Zürich'], 'canton of zurich': ['CH', 'Zürich'],
  'vaud': ['CH', 'Vaud'], 'geneva canton': ['CH', 'Geneva'], 'dubai emirate': ['AE', 'Dubai'], 'abu dhabi emirate': ['AE', 'Abu Dhabi'],
  'kuala lumpur federal territory': ['MY', 'Kuala Lumpur'], 'selangor': ['MY', 'Selangor'], 'dki jakarta': ['ID', 'Jakarta'],
  'buenos aires province': ['AR', 'Buenos Aires'], 'cordoba province': ['AR', 'Córdoba'], 'antioquia': ['CO', 'Antioquia'],
  'cundinamarca': ['CO', 'Cundinamarca'], 'region metropolitana': ['CL', 'Región Metropolitana'], 'gauteng': ['ZA', 'Gauteng'],
  'western cape': ['ZA', 'Western Cape'], 'lagos state': ['NG', 'Lagos'], 'nairobi county': ['KE', 'Nairobi'], 'ho chi minh': ['VN', 'Ho Chi Minh City'],
  'tbilisi region': ['GE', 'Tbilisi'], 'adjara': ['GE', 'Adjara'], 'imereti': ['GE', 'Imereti'],
};

/** Canadian and Australian region codes. US codes win for WA and NT is shared; the resolver decides by city. */
export const CA_PROVINCE_CODES: Record<string, string> = {
  AB: 'Alberta', BC: 'British Columbia', MB: 'Manitoba', NB: 'New Brunswick', NL: 'Newfoundland and Labrador', NS: 'Nova Scotia',
  NT: 'Northwest Territories', NU: 'Nunavut', ON: 'Ontario', PE: 'Prince Edward Island', QC: 'Quebec', SK: 'Saskatchewan', YT: 'Yukon',
  PQ: 'Quebec',
};
export const AU_STATE_CODES: Record<string, string> = {
  NSW: 'New South Wales', VIC: 'Victoria', QLD: 'Queensland', WA: 'Western Australia', SA: 'South Australia', TAS: 'Tasmania',
  ACT: 'Australian Capital Territory', NT: 'Northern Territory',
};

// World cities by country (major cities, capitals and tech hubs; native and English spellings).
const WORLD_CITIES: Record<string, string> = {
  CA: 'Toronto|Montreal|Montréal|Vancouver|Calgary|Edmonton|Ottawa|Winnipeg|Quebec City|Québec|Hamilton|Kitchener|Waterloo|London|Victoria|Halifax|Oshawa|Windsor|Saskatoon|Regina|Barrie|Sherbrooke|Guelph|Kelowna|Abbotsford|Kingston|Burnaby|Surrey|Richmond|Markham|Mississauga|Brampton|Vaughan|Oakville|Burlington|Richmond Hill|Laval|Gatineau|Longueuil|St. John\'s|Saint John|Fredericton|Moncton|Charlottetown|Whitehorse|Yellowknife|Iqaluit|Sudbury|Greater Sudbury|Thunder Bay|Sault Ste. Marie|Timmins|North Bay|Peterborough|Belleville|Cornwall|Brantford|St. Catharines|Niagara Falls|Cambridge|Nanaimo|Kamloops|Prince George|Prince Rupert|Red Deer|Lethbridge|Medicine Hat|Fort McMurray|Grande Prairie|Brandon|Moose Jaw|Sechelt|Whistler|North Vancouver|West Vancouver|Coquitlam|New Westminster|Langley|Delta|Etobicoke|Scarborough|North York|Pickering|Ajax|Whitby|Milton|Newmarket|Aurora|Trois-Rivières|Saguenay|Levis|Lévis|Terrebonne|Dartmouth|Sydney',
  GB: 'London|Manchester|Birmingham|Leeds|Glasgow|Liverpool|Edinburgh|Bristol|Sheffield|Newcastle|Newcastle upon Tyne|Nottingham|Leicester|Cardiff|Belfast|Southampton|Brighton|Oxford|Cambridge|Reading|Milton Keynes|Aberdeen|Dundee|Swansea|York|Bath|Coventry|Solihull|Derby|Plymouth|Portsmouth|Norwich|Exeter|Cheltenham|Gloucester|Guildford|Woking|Slough|Watford|St Albans|Luton|Northampton|Peterborough|Ipswich|Colchester|Chelmsford|Maidstone|Canterbury|Crawley|Basingstoke|Swindon|Bournemouth|Poole|Stoke-on-Trent|Wolverhampton|Sunderland|Middlesbrough|Bradford|Huddersfield|Wakefield|Hull|Kingston upon Hull|Lincoln|Chester|Warrington|Stockport|Bolton|Preston|Blackpool|Lancaster|Carlisle|Durham|Harrogate|Inverness|Stirling|Perth|Livingston|Paisley|Newport|Wrexham|Derry|Londonderry|Lisburn|Canary Wharf|Shoreditch|Croydon|Richmond upon Thames|Wimbledon|Uxbridge|Hemel Hempstead|Stevenage|Hatfield|Farnborough|Bracknell|Maidenhead|High Wycombe|Aylesbury|Bedford|Loughborough|Leamington Spa|Warwick|Worcester|Hereford|Shrewsbury|Telford|Stafford|Crewe|Macclesfield|Salford|Trafford|Wigan|Oldham|Rochdale|Doncaster|Rotherham|Barnsley|Grimsby|Scunthorpe',
  IE: 'Dublin|Cork|Galway|Limerick|Waterford|Kilkenny|Drogheda|Dundalk|Sligo|Athlone|Wexford|Letterkenny|Ennis|Tralee|Carlow|Naas|Swords|Dún Laoghaire|Dun Laoghaire|Bray|Shannon',
  DE: 'Berlin|Munich|München|Hamburg|Frankfurt|Frankfurt am Main|Cologne|Köln|Stuttgart|Düsseldorf|Dusseldorf|Dortmund|Essen|Leipzig|Bremen|Dresden|Hanover|Hannover|Nuremberg|Nürnberg|Duisburg|Bochum|Wuppertal|Bielefeld|Bonn|Münster|Munster|Karlsruhe|Mannheim|Augsburg|Wiesbaden|Mainz|Heidelberg|Darmstadt|Freiburg|Potsdam|Kiel|Rostock|Aachen|Regensburg|Ingolstadt|Wolfsburg|Ulm|Erlangen|Jena|Göttingen|Walldorf|Gütersloh|Paderborn|Kassel|Halle|Magdeburg|Erfurt|Saarbrücken|Braunschweig|Oldenburg|Osnabrück|Würzburg|Heilbronn|Pforzheim|Reutlingen|Koblenz|Trier|Lübeck|Chemnitz|Zwickau',
  FR: 'Paris|Marseille|Lyon|Toulouse|Nice|Nantes|Strasbourg|Montpellier|Bordeaux|Lille|Rennes|Reims|Grenoble|Toulon|Dijon|Angers|Nîmes|Nimes|Aix-en-Provence|Clermont-Ferrand|Le Mans|Brest|Tours|Amiens|Limoges|Annecy|Perpignan|Metz|Besançon|Orléans|Rouen|Caen|Nancy|Sophia Antipolis|La Défense|La Defense|Boulogne-Billancourt|Saint-Denis|Issy-les-Moulineaux|Neuilly-sur-Seine|Levallois-Perret|Courbevoie|Nanterre|Versailles|Massy|Saclay|Cergy|Mulhouse|Pau|Bayonne|La Rochelle|Poitiers|Valence|Chambéry|Avignon',
  ES: 'Madrid|Barcelona|Valencia|Seville|Sevilla|Zaragoza|Málaga|Malaga|Murcia|Palma|Palma de Mallorca|Las Palmas|Bilbao|Alicante|Córdoba|Cordoba|Valladolid|Vigo|Gijón|A Coruña|La Coruña|Granada|Vitoria|San Sebastián|Donostia|Santander|Pamplona|Salamanca|Tarragona|Girona|Castellón|Badajoz|Oviedo|Cádiz|Jerez|Santa Cruz de Tenerife|Burgos|León|Almería|Huelva|Logroño|Lleida',
  PT: 'Lisbon|Lisboa|Porto|Braga|Coimbra|Aveiro|Faro|Funchal|Setúbal|Setubal|Guimarães|Évora|Leiria|Viseu|Amadora|Oeiras|Cascais|Sintra|Matosinhos|Maia|Vila Nova de Gaia',
  IT: 'Rome|Roma|Milan|Milano|Naples|Napoli|Turin|Torino|Palermo|Genoa|Genova|Bologna|Florence|Firenze|Bari|Catania|Venice|Venezia|Verona|Messina|Padua|Padova|Trieste|Brescia|Parma|Modena|Reggio Emilia|Perugia|Livorno|Cagliari|Pisa|Bergamo|Trento|Bolzano|Vicenza|Ancona|Pescara|Salerno|Lecce|Como|Monza|Siena|Ferrara|Ravenna|Rimini|Udine|Treviso|Novara|Pavia|Varese|Lucca',
  NL: 'Amsterdam|Rotterdam|The Hague|Den Haag|Utrecht|Eindhoven|Groningen|Tilburg|Almere|Breda|Nijmegen|Apeldoorn|Haarlem|Arnhem|Enschede|Amersfoort|Zaanstad|Den Bosch|\'s-Hertogenbosch|Zwolle|Leiden|Maastricht|Dordrecht|Delft|Hilversum|Hoofddorp|Schiphol|Amstelveen|Wageningen|Veldhoven|Leeuwarden',
  BE: 'Brussels|Bruxelles|Brussel|Antwerp|Antwerpen|Anvers|Ghent|Gent|Gand|Charleroi|Liège|Liege|Bruges|Brugge|Namur|Leuven|Louvain|Mons|Mechelen|Aalst|Hasselt|Kortrijk|Ostend|Oostende|Wavre|Louvain-la-Neuve|Zaventem|Diegem',
  LU: 'Luxembourg City|Esch-sur-Alzette|Differdange|Dudelange|Kirchberg',
  CH: 'Zurich|Zürich|Geneva|Genève|Geneve|Basel|Bern|Berne|Lausanne|Lucerne|Luzern|St. Gallen|Lugano|Winterthur|Zug|Biel|Thun|Fribourg|Neuchâtel|Schaffhausen|Baar|Schlieren|Sion',
  AT: 'Vienna|Wien|Graz|Linz|Salzburg|Innsbruck|Klagenfurt|Villach|Wels|Sankt Pölten|St. Pölten|Dornbirn|Bregenz',
  DK: 'Copenhagen|København|Aarhus|Århus|Odense|Aalborg|Esbjerg|Randers|Kolding|Horsens|Vejle|Roskilde|Lyngby|Kongens Lyngby|Herning|Billund',
  SE: 'Stockholm|Gothenburg|Göteborg|Malmö|Malmo|Uppsala|Västerås|Örebro|Linköping|Linkoping|Helsingborg|Jönköping|Norrköping|Lund|Umeå|Gävle|Borås|Södertälje|Eskilstuna|Karlstad|Växjö|Luleå|Sundsvall|Kista|Solna',
  NO: 'Oslo|Bergen|Trondheim|Stavanger|Drammen|Fredrikstad|Kristiansand|Sandnes|Tromsø|Tromso|Sarpsborg|Skien|Ålesund|Bodø|Lysaker|Fornebu|Asker|Bærum',
  FI: 'Helsinki|Espoo|Tampere|Vantaa|Oulu|Turku|Jyväskylä|Lahti|Kuopio|Pori|Joensuu|Lappeenranta|Vaasa',
  IS: 'Reykjavik|Reykjavík|Kópavogur|Hafnarfjörður|Akureyri',
  PL: 'Warsaw|Warszawa|Kraków|Krakow|Cracow|Łódź|Lodz|Wrocław|Wroclaw|Poznań|Poznan|Gdańsk|Gdansk|Szczecin|Bydgoszcz|Lublin|Białystok|Bialystok|Katowice|Gdynia|Częstochowa|Radom|Toruń|Torun|Sosnowiec|Rzeszów|Rzeszow|Kielce|Gliwice|Olsztyn|Bielsko-Biała|Opole|Sopot',
  CZ: 'Prague|Praha|Brno|Ostrava|Plzeň|Plzen|Liberec|Olomouc|České Budějovice|Hradec Králové|Pardubice|Zlín',
  SK: 'Bratislava|Košice|Kosice|Prešov|Žilina|Nitra|Banská Bystrica|Trnava',
  HU: 'Budapest|Debrecen|Szeged|Miskolc|Pécs|Pecs|Győr|Gyor|Nyíregyháza|Kecskemét|Székesfehérvár',
  RO: 'Bucharest|București|Bucuresti|Cluj-Napoca|Cluj|Timișoara|Timisoara|Iași|Iasi|Constanța|Constanta|Craiova|Brașov|Brasov|Galați|Ploiești|Oradea|Sibiu|Arad|Pitești|Bacău|Târgu Mureș',
  BG: 'Sofia|Plovdiv|Varna|Burgas|Ruse|Stara Zagora|Pleven',
  GR: 'Athens|Athina|Thessaloniki|Patras|Heraklion|Larissa|Volos|Ioannina|Chania',
  HR: 'Zagreb|Split|Rijeka|Osijek|Zadar|Pula|Dubrovnik|Varaždin',
  SI: 'Ljubljana|Maribor|Celje|Kranj|Koper',
  RS: 'Belgrade|Beograd|Novi Sad|Niš|Nis|Kragujevac|Subotica',
  BA: 'Sarajevo|Banja Luka|Tuzla|Mostar',
  ME: 'Podgorica|Budva',
  MK: 'Skopje',
  AL: 'Tirana|Tiranë|Durrës',
  EE: 'Tallinn|Tartu|Narva|Pärnu',
  LV: 'Riga|Rīga|Daugavpils|Liepāja',
  LT: 'Vilnius|Kaunas|Klaipėda|Klaipeda|Šiauliai',
  UA: 'Kyiv|Kiev|Kharkiv|Odesa|Odessa|Dnipro|Lviv|Zaporizhzhia|Vinnytsia|Ivano-Frankivsk|Chernivtsi|Ternopil|Uzhhorod|Lutsk|Poltava|Mykolaiv|Kherson|Sumy|Zhytomyr',
  BY: 'Minsk|Gomel|Grodno|Brest|Vitebsk',
  MD: 'Chișinău|Chisinau',
  RU: 'Moscow|Moskva|Saint Petersburg|St. Petersburg|Novosibirsk|Yekaterinburg|Kazan|Nizhny Novgorod|Samara|Omsk|Rostov-on-Don|Ufa|Krasnoyarsk|Perm|Voronezh|Volgograd|Krasnodar|Sochi|Kaliningrad|Tomsk|Innopolis',
  GE: 'Tbilisi|Batumi|Kutaisi|Rustavi|Zugdidi|Gori|Poti|Telavi|Kobuleti|Borjomi|Mtskheta',
  AM: 'Yerevan|Gyumri',
  AZ: 'Baku|Ganja',
  TR: 'Istanbul|İstanbul|Ankara|Izmir|İzmir|Bursa|Antalya|Adana|Konya|Gaziantep|Kayseri|Eskişehir|Eskisehir|Mersin|Kocaeli|Samsun|Trabzon',
  CY: 'Nicosia|Limassol|Larnaca|Paphos',
  MT: 'Valletta|Sliema|St. Julian\'s|St Julians|Birkirkara|Mosta|Qormi|Msida|Gżira',
  IL: 'Tel Aviv|Tel Aviv-Yafo|Jerusalem|Haifa|Rishon LeZion|Petah Tikva|Petah Tiqva|Ashdod|Netanya|Beersheba|Be\'er Sheva|Holon|Bnei Brak|Ramat Gan|Rehovot|Herzliya|Kfar Saba|Ra\'anana|Raanana|Hod HaSharon|Modiin|Caesarea|Yokneam|Airport City|Or Yehuda|Bat Yam|Givatayim|Lod|Ramla|Nazareth|Eilat',
  LB: 'Beirut|Tripoli|Sidon|Tyre|Jounieh|Byblos',
  JO: 'Amman|Zarqa|Irbid|Aqaba',
  SA: 'Riyadh|Jeddah|Mecca|Makkah|Medina|Madinah|Dammam|Khobar|Al Khobar|Dhahran|Tabuk|Abha|Jizan|Jazan|Taif|Buraidah|Hail|Najran|Yanbu|Jubail|NEOM|Al Kharj|Qassim|Khamis Mushait|Hofuf|Al Ahsa',
  AE: 'Dubai|Abu Dhabi|Sharjah|Al Ain|Ajman|Ras Al Khaimah|Fujairah|Umm Al Quwain',
  QA: 'Doha|Al Rayyan|Lusail|Al Wakrah',
  KW: 'Kuwait City|Hawalli|Salmiya',
  BH: 'Manama|Muharraq',
  OM: 'Muscat|Salalah|Sohar',
  EG: 'Cairo|Alexandria|Giza|New Cairo|Sheikh Zayed|6th of October|Port Said|Suez|Luxor|Aswan|Mansoura|Tanta|Hurghada|Sharm El Sheikh',
  MA: 'Casablanca|Rabat|Marrakech|Marrakesh|Fes|Fez|Tangier|Tanger|Agadir|Meknes|Oujda|Kenitra|Tetouan',
  TN: 'Tunis|Sfax|Sousse|Ariana',
  DZ: 'Algiers|Oran|Constantine|Annaba',
  NG: 'Lagos|Abuja|Kano|Ibadan|Port Harcourt|Benin City|Kaduna|Enugu|Ikeja|Lekki|Victoria Island',
  GH: 'Accra|Kumasi|Tamale|Takoradi|Tema',
  KE: 'Nairobi|Mombasa|Kisumu|Nakuru|Eldoret',
  ET: 'Addis Ababa',
  UG: 'Kampala|Entebbe',
  TZ: 'Dar es Salaam|Dodoma|Arusha|Zanzibar',
  RW: 'Kigali',
  ZA: 'Johannesburg|Cape Town|Durban|Pretoria|Port Elizabeth|Gqeberha|Bloemfontein|Sandton|Centurion|Midrand|Stellenbosch|East London|Pietermaritzburg|Polokwane|Nelspruit|Randburg|Rosebank',
  SN: 'Dakar',
  CI: 'Abidjan|Yamoussoukro',
  CM: 'Douala|Yaoundé|Yaounde',
  IN: 'Mumbai|Bombay|Delhi|New Delhi|Bangalore|Bengaluru|Hyderabad|Ahmedabad|Chennai|Madras|Kolkata|Calcutta|Pune|Surat|Jaipur|Lucknow|Kanpur|Nagpur|Indore|Thane|Bhopal|Visakhapatnam|Vizag|Patna|Vadodara|Ghaziabad|Ludhiana|Agra|Nashik|Faridabad|Meerut|Rajkot|Varanasi|Srinagar|Aurangabad|Amritsar|Navi Mumbai|Allahabad|Prayagraj|Ranchi|Howrah|Coimbatore|Jabalpur|Gwalior|Vijayawada|Jodhpur|Madurai|Raipur|Kota|Chandigarh|Guwahati|Mysore|Mysuru|Gurgaon|Gurugram|Noida|Greater Noida|Kochi|Cochin|Thiruvananthapuram|Trivandrum|Bhubaneswar|Dehradun|Mangalore|Mangaluru|Trichy|Tiruchirappalli|Hubli|Belgaum|Goa|Panaji|Pondicherry|Puducherry|Vellore|Manipal|Gandhinagar|Salem|Tirupati|Warangal|Kozhikode|Calicut|Thrissur|Jamshedpur|Dhanbad|Siliguri|Udaipur|Ajmer|Bikaner|Aligarh|Bareilly|Moradabad|Gorakhpur|Jammu|Shimla|Mohali|Panchkula|Zirakpur|Sonipat|Karnal|Hosur|Whitefield|Electronic City|Hinjewadi|Powai|Andheri|Bandra|Malad|Goregaon|Vikhroli|Airoli|Magarpatta|Kharadi|Baner|HITEC City|Gachibowli|Madhapur|Secunderabad|Guindy|Sholinganallur|Perungudi|Siruseri|Tidel Park',
  PK: 'Karachi|Lahore|Islamabad|Rawalpindi|Faisalabad|Multan|Peshawar|Quetta|Sialkot|Hyderabad (Pakistan)',
  BD: 'Dhaka|Chittagong|Chattogram|Khulna|Sylhet|Rajshahi',
  LK: 'Colombo|Kandy|Galle|Negombo',
  NP: 'Kathmandu|Pokhara|Lalitpur',
  CN: 'Beijing|Shanghai|Guangzhou|Shenzhen|Chengdu|Chongqing|Tianjin|Wuhan|Hangzhou|Nanjing|Xi\'an|Xian|Suzhou|Zhengzhou|Changsha|Shenyang|Qingdao|Dalian|Xiamen|Ningbo|Hefei|Fuzhou|Jinan|Kunming|Harbin|Dongguan|Foshan|Zhuhai|Wuxi|Changzhou|Nanning|Guiyang|Taiyuan|Shijiazhuang|Nanchang|Urumqi|Lanzhou|Hohhot|Haikou|Sanya|Zhongshan|Huizhou|Jiaxing|Shaoxing',
  HK: 'Hong Kong|Kowloon|Central|Wan Chai|Tsim Sha Tsui|Causeway Bay|Quarry Bay|Kwun Tong|Sha Tin|Tsuen Wan|Cyberport',
  MO: 'Macau|Macao|Taipa|Cotai',
  TW: 'Taipei|New Taipei|Kaohsiung|Taichung|Tainan|Hsinchu|Taoyuan|Keelung',
  JP: 'Tokyo|東京|Osaka|大阪|Yokohama|Nagoya|Sapporo|Fukuoka|福岡|Kobe|Kyoto|京都|Kawasaki|Saitama|Hiroshima|Sendai|Chiba|Kitakyushu|Sakai|Niigata|Hamamatsu|Kumamoto|Okayama|Shizuoka|Naha|Okinawa|Kanazawa|Nara|Tsukuba|Shibuya|Shinjuku|Minato|Chiyoda|Chuo|Roppongi|Marunouchi|Shinagawa|Meguro|Setagaya',
  KR: 'Seoul|서울|Busan|Incheon|Daegu|Daejeon|Gwangju|Suwon|Ulsan|Seongnam|Pangyo|Goyang|Yongin|Bucheon|Cheongju|Jeonju|Changwon|Jeju|Gangnam|Hongdae|Yeonnam|Itaewon|Seongsu|Yeouido|Pohang|Sejong',
  SG: 'Singapore|One-North|Jurong|Changi|Tampines|Woodlands|Raffles Place|Marina Bay|Tanjong Pagar',
  MY: 'Kuala Lumpur|KL|George Town|Penang|Johor Bahru|Ipoh|Shah Alam|Petaling Jaya|Cyberjaya|Putrajaya|Subang Jaya|Kota Kinabalu|Kuching|Malacca|Melaka|Seremban|Klang|Bangsar|Puchong',
  ID: 'Jakarta|Surabaya|Bandung|Medan|Semarang|Makassar|Palembang|Tangerang|Bekasi|Depok|Denpasar|Bali|Yogyakarta|Malang|Batam|Bogor|South Jakarta|Jakarta Selatan',
  TH: 'Bangkok|Chiang Mai|Phuket|Pattaya|Khon Kaen|Nonthaburi|Hat Yai|Chonburi|Rayong',
  VN: 'Ho Chi Minh City|Saigon|Hanoi|Hà Nội|Ha Noi|Da Nang|Đà Nẵng|Haiphong|Hai Phong|Can Tho|Nha Trang|Hue|Bien Hoa|Vung Tau|HCMC',
  PH: 'Manila|Quezon City|Makati|Taguig|Pasig|Cebu|Cebu City|Davao|Davao City|Mandaluyong|Parañaque|Paranaque|Pasay|Caloocan|Las Piñas|Muntinlupa|Alabang|Bonifacio Global City|BGC|Ortigas|Iloilo|Iloilo City|Bacolod|Cagayan de Oro|Baguio|Clark|Angeles|Santa Rosa|Lipa|Batangas',
  KH: 'Phnom Penh|Siem Reap',
  AU: 'Sydney|Melbourne|Brisbane|Perth|Adelaide|Gold Coast|Canberra|Newcastle|Wollongong|Hobart|Geelong|Townsville|Cairns|Darwin|Toowoomba|Ballarat|Bendigo|Launceston|Mackay|Rockhampton|Sunshine Coast|Parramatta|North Sydney|Chatswood|Macquarie Park|Fremantle|Bunbury|Albury|Wagga Wagga',
  NZ: 'Auckland|Wellington|Christchurch|Hamilton|Tauranga|Dunedin|Palmerston North|Napier|Nelson|Rotorua|New Plymouth|Whangarei|Invercargill|Queenstown',
  BR: 'São Paulo|Sao Paulo|Rio de Janeiro|Brasília|Brasilia|Salvador|Fortaleza|Belo Horizonte|Manaus|Curitiba|Recife|Goiânia|Goiania|Belém|Belem|Porto Alegre|Guarulhos|Campinas|São Luís|Sao Luis|São Gonçalo|Maceió|Maceio|Duque de Caxias|Natal|Teresina|Campo Grande|Nova Iguaçu|São Bernardo do Campo|João Pessoa|Joao Pessoa|Santo André|Osasco|Jaboatão|São José dos Campos|Ribeirão Preto|Ribeirao Preto|Uberlândia|Uberlandia|Sorocaba|Contagem|Aracaju|Feira de Santana|Cuiabá|Cuiaba|Joinville|Juiz de Fora|Londrina|Aparecida de Goiânia|Niterói|Niteroi|Ananindeua|Porto Velho|Serra|Caxias do Sul|Macapá|Florianópolis|Florianopolis|Vila Velha|Mauá|São João de Meriti|Santos|Mogi das Cruzes|Betim|Diadema|Campina Grande|Jundiaí|Jundiai|Maringá|Maringa|Montes Claros|Piracicaba|Carapicuíba|Olinda|Cariacica|Rio Branco|Anápolis|Bauru|Vitória|Vitoria|Caucaia|Itaquaquecetuba|São Vicente|Blumenau|Barueri|Alphaville|São Carlos|Sao Carlos|Pelotas|Petrópolis|Canoas|Palmas|Boa Vista|Ponta Grossa|Franca|Cascavel|Paulista|Uberaba|Limeira|Taubaté|Santa Maria|Gravataí|Guarujá|Novo Hamburgo|Chapecó|Itajaí|Balneário Camboriú|Indaiatuba|Valinhos|Hortolândia|Sumaré|Americana|Lajeado|Passo Fundo|Criciúma|Tubarão|Lages|Ipatinga|Governador Valadares|Divinópolis|Sete Lagoas|Poços de Caldas|Varginha|Pouso Alegre|Lavras|Viçosa|Ouro Preto|Nova Lima',
  AR: 'Buenos Aires|CABA|Córdoba|Cordoba|Rosario|Mendoza|La Plata|San Miguel de Tucumán|Tucumán|Mar del Plata|Salta|Santa Fe|San Juan|Resistencia|Neuquén|Neuquen|Bahía Blanca|Posadas|Paraná|San Luis|Bariloche|Ushuaia|Pilar|Tigre|San Isidro|Vicente López|Martínez|Olivos',
  CL: 'Santiago|Santiago de Chile|Valparaíso|Valparaiso|Viña del Mar|Concepción|Concepcion|Antofagasta|La Serena|Temuco|Rancagua|Iquique|Puerto Montt|Arica|Talca|Chillán|Las Condes|Providencia|Vitacura|Ñuñoa',
  CO: 'Bogotá|Bogota|Medellín|Medellin|Cali|Barranquilla|Cartagena|Bucaramanga|Cúcuta|Pereira|Santa Marta|Ibagué|Manizales|Pasto|Villavicencio|Armenia|Neiva|Envigado|Sabaneta|Itagüí|Rionegro|Chía',
  PE: 'Lima|Arequipa|Trujillo|Chiclayo|Cusco|Cuzco|Piura|Iquitos|Huancayo|Callao|Miraflores|San Isidro|Surco|La Molina',
  EC: 'Quito|Guayaquil|Cuenca|Manta|Ambato|Loja',
  UY: 'Montevideo|Punta del Este|Salto|Paysandú|Colonia del Sacramento',
  PY: 'Asunción|Asuncion|Ciudad del Este|Encarnación',
  BO: 'La Paz|Santa Cruz de la Sierra|Cochabamba|Sucre|El Alto',
  VE: 'Caracas|Maracaibo|Valencia|Barquisimeto|Maracay|Mérida',
  CR: 'San José|San Jose|Heredia|Alajuela|Cartago|Escazú|Escazu|Santa Ana|Liberia|Belén|Belen',
  PA: 'Panama City|Ciudad de Panamá|Colón|David',
  GT: 'Guatemala City|Ciudad de Guatemala|Quetzaltenango|Antigua Guatemala',
  SV: 'San Salvador|Santa Tecla|Antiguo Cuscatlán',
  HN: 'Tegucigalpa|San Pedro Sula',
  NI: 'Managua|León|Granada',
  DO: 'Santo Domingo|Santiago de los Caballeros|Punta Cana|La Romana|Puerto Plata',
  JM: 'Kingston|Montego Bay|Ocho Rios|Spanish Town|Portmore',
  TT: 'Port of Spain|San Fernando|Chaguanas',
  BS: 'Nassau|Freeport',
  BB: 'Bridgetown',
  MX: 'Mexico City|Ciudad de México|Ciudad de Mexico|CDMX|Guadalajara|Monterrey|Puebla|Tijuana|León|Leon|Juárez|Ciudad Juárez|Ciudad Juarez|Zapopan|Mérida|Merida|San Luis Potosí|Aguascalientes|Hermosillo|Saltillo|Mexicali|Culiacán|Culiacan|Querétaro|Queretaro|Santiago de Querétaro|Chihuahua|Morelia|Toluca|Cancún|Cancun|Reynosa|Torreón|Torreon|Acapulco|Tlaquepaque|Veracruz|Villahermosa|Xalapa|Oaxaca|Tuxtla Gutiérrez|Durango|Mazatlán|Mazatlan|Ensenada|Matamoros|Nuevo Laredo|Irapuato|Celaya|Tampico|Cuernavaca|Pachuca|Playa del Carmen|Puerto Vallarta|San Pedro Garza García|San Pedro Garza Garcia|Apodaca|Guadalupe|Santa Catarina|Tlalnepantla|Naucalpan|Ecatepec|Nezahualcóyotl|Tecámac|Tecamac|Cuautitlán|Tultitlán|Atizapán|Huixquilucan|Santa Fe|Polanco|Coyoacán|Benito Juárez|Miguel Hidalgo|Cuauhtémoc|Álvaro Obregón|Tlalpan|Iztapalapa|Azcapotzalco|Ciudad Obregón|Los Mochis|La Paz|Los Cabos|San José del Cabo|Cabo San Lucas|Zacatecas|Colima|Manzanillo|Tepic|Campeche|Chetumal|Tulum',
  KZ: 'Almaty|Astana|Nur-Sultan|Shymkent|Karaganda',
  UZ: 'Tashkent|Samarkand',
  MN: 'Ulaanbaatar|Ulan Bator',
};

/** World city key -> countries it is in (outside the US). */
export const WORLD_CITY_COUNTRIES: Map<string, string[]> = (() => {
  const m = new Map<string, string[]>();
  const fold = (s: string) => s.normalize('NFD').replace(new RegExp('[\\u{300}-\\u{36f}]', 'gu'), '').toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9\u{3040}-\u{9fff}\u{ac00}-\u{d7af}]+/gu, ' ').trim();
  for (const [cc, list] of Object.entries(WORLD_CITIES)) {
    for (const name of list.split('|')) {
      const k = fold(name);
      if (!k) continue;
      const cur = m.get(k) ?? [];
      if (!cur.includes(cc)) cur.push(cc);
      m.set(k, cur);
      const alt = k.replace(/^st /, 'saint ').replace(/^saint /, 'st ');
      if (alt !== k) { const c2 = m.get(alt) ?? []; if (!c2.includes(cc)) c2.push(cc); m.set(alt, c2); }
    }
  }
  return m;
})();

/** Display names of world cities, keyed like WORLD_CITY_COUNTRIES (first spelling wins). */
export const WORLD_CITY_NAMES: Map<string, string> = (() => {
  const m = new Map<string, string>();
  const fold = (s: string) => s.normalize('NFD').replace(new RegExp('[\\u{300}-\\u{36f}]', 'gu'), '').toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9\u{3040}-\u{9fff}\u{ac00}-\u{d7af}]+/gu, ' ').trim();
  for (const list of Object.values(WORLD_CITIES)) for (const name of list.split('|')) { const k = fold(name); if (k && !m.has(k)) m.set(k, name); }
  return m;
})();

/**
 * A bare city name that exists both in the US and abroad (or in several countries): the reading when the posting
 * gives no other clue. "" means no reading dominates, so the country stays unknown.
 * Values: an ISO country, or "US-XX" for a US state.
 */
export const GLOBAL_DOMINANT: Record<string, string> = {
  'london': 'GB', 'paris': 'FR', 'dublin': 'IE', 'birmingham': 'GB', 'manchester': 'GB', 'cambridge': '', 'vancouver': 'CA',
  'hamilton': '', 'kingston': '', 'melbourne': 'AU', 'sydney': 'AU', 'perth': 'AU', 'athens': '', 'rome': 'IT', 'naples': '',
  'florence': '', 'venice': '', 'toledo': 'US-OH', 'alexandria': '', 'berlin': 'DE', 'moscow': 'RU', 'delhi': 'IN', 'salem': '',
  'lebanon': 'LB', 'jordan': 'JO', 'mexico': 'MX', 'peru': 'PE', 'cordoba': '', 'valencia': 'ES', 'leon': '', 'santiago': 'CL',
  'victoria': '', 'windsor': '', 'waterloo': '', 'oxford': 'GB', 'durham': '', 'newcastle': 'GB', 'richmond': 'US-VA',
  'aberdeen': 'GB', 'glasgow': 'GB', 'edinburgh': 'GB', 'bristol': 'GB', 'plymouth': '', 'worcester': '', 'kent': '',
  'surrey': '', 'burlington': '', 'sudbury': 'CA', 'guelph': 'CA', 'lancaster': '', 'lincoln': '', 'dover': '', 'exeter': '',
  'portsmouth': '', 'newport': '', 'chester': '', 'bedford': '', 'warwick': '', 'reading': 'GB', 'london ky': 'US-KY',
  'granada': 'ES', 'santa cruz': '', 'la paz': 'BO', 'san jose': 'US-CA', 'santa ana': 'US-CA', 'guadalupe': '',
  'santa fe': '', 'san juan': 'US-PR', 'merida': 'MX', 'trujillo': 'PE', 'hyderabad': 'IN', 'tripoli': '', 'brest': 'FR',
  'georgia': 'US-GA', 'panama city': '', 'freeport': '', 'sydney ns': 'CA', 'nazareth': '', 'central': '', 'serra': 'BR',
  'paulista': 'BR', 'clark': '', 'angeles': 'PH', 'delta': '', 'milton': '', 'aurora': 'US-CO', 'markham': 'CA',
  'london on': 'CA', 'orange': 'US-CA', 'troy': '', 'albany': 'US-NY', 'springfield': 'US', 'arlington': 'US', 'kl': 'MY',
  'cancun': 'MX', 'monterrey': 'MX', 'guadalajara': 'MX', 'tijuana': 'MX', 'acapulco': 'MX', 'bangalore': 'IN', 'goa': 'IN',
  'amsterdam': 'NL', 'hudson': 'US', 'palmas': 'BR', 'belem': 'BR', 'belen': '', 'liberia': '', 'david': 'PA',
};
