// One-off generator: reads the Helvetica and Helvetica-Bold glyph widths and the WinAnsiEncoding glyph list from
// the PDF.js bundle inside unpdf (pdf.js src/core/metrics.js and src/core/encodings.js, Apache-2.0; the widths come
// from Adobe's Core 14 AFM files) and writes src/render/helvetica-metrics.ts: one width per WinAnsi byte.
// Run: node scripts/extract-helvetica-metrics.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const bundle = readFileSync(join(here, '..', 'node_modules', 'unpdf', 'dist', 'pdfjs.mjs'), 'utf8');

function table(name: string): Map<string, number> {
  const key = name.includes('-') ? `e[\`${name}\`]=getLookupTableFactory(function(e){` : `e.${name}=getLookupTableFactory(function(e){`;
  const start = bundle.indexOf(key);
  if (start < 0) throw new Error(`metrics for ${name} not found`);
  const body = bundle.slice(start + key.length, bundle.indexOf('})', start));
  const out = new Map<string, number>();
  for (const m of body.matchAll(/e(?:\.([A-Za-z0-9_]+)|\[`([^`]+)`\])=(\d+)/g)) out.set((m[1] ?? m[2])!, Number(m[3]));
  return out;
}

function winAnsi(): string[] {
  // The bundle stores each encoding as one dot-joined string; WinAnsi is the one with "asciitilde.bullet.Euro".
  const i = bundle.indexOf('asciitilde.bullet.Euro.bullet.quotesinglbase');
  if (i < 0) throw new Error('WinAnsiEncoding not found');
  const start = bundle.lastIndexOf('`', i);
  const end = bundle.indexOf('`', i);
  return bundle.slice(start + 1, end).split('.');
}

const enc = winAnsi();
if (enc.length !== 256) throw new Error(`WinAnsiEncoding has ${enc.length} entries`);
const reg = table('Helvetica');
const bold = table('Helvetica-Bold');
const widths = (t: Map<string, number>) => enc.map((g) => (g ? (t.get(g) ?? 0) : 0));
const src = `// GENERATED by scripts/extract-helvetica-metrics.ts. Do not edit.
// Glyph widths (1/1000 em) of the standard PDF fonts Helvetica and Helvetica-Bold, one per WinAnsiEncoding byte.
// Source: pdf.js src/core/metrics.js and src/core/encodings.js (Apache-2.0), as bundled in unpdf 1.8.1; the widths
// are Adobe's Core 14 AFM metrics. See THIRD_PARTY_NOTICES.md.

export const WIN_ANSI_GLYPHS: readonly string[] = ${JSON.stringify(enc)};
export const HELVETICA_WIDTHS: readonly number[] = ${JSON.stringify(widths(reg))};
export const HELVETICA_BOLD_WIDTHS: readonly number[] = ${JSON.stringify(widths(bold))};
`;
writeFileSync(join(here, '..', 'src', 'render', 'helvetica-metrics.ts'), src);
console.log('wrote src/render/helvetica-metrics.ts', reg.size, bold.size);
